// Thesis presentation generator — agent-centered defense deck
// Usage: npm install pptxgenjs && node scripts/build_thesis_presentation_agent_zh.js outputs/papers/thesis_presentation_agent_zh.pptx

const fs = require('fs');
const path = require('path');
const pptxgen = require('pptxgenjs');

const pptx = new pptxgen();
pptx.defineLayout({ name: 'WIDE', width: 13.333, height: 7.5 });
pptx.layout = 'WIDE';
pptx.author = '林昀佑';
pptx.company = 'NCUE';
pptx.subject = 'Sparse-sensing indoor spatial digital twin thesis defense';
pptx.title = '單房間非連網家電環境影響學習之稀疏感測空間數位孿生原型';
pptx.lang = 'zh-TW';
pptx.theme = { headFontFace: 'Noto Sans CJK TC', bodyFontFace: 'Noto Sans CJK TC', lang: 'zh-TW' };

const C = { bg:'F7F8FA', text:'111827', muted:'4B5563', line:'E5E7EB', white:'FFFFFF',
  blue:'1D4ED8', blue2:'DBEAFE', green:'047857', green2:'D1FAE5', amber:'B45309', amber2:'FEF3C7',
  purple:'6D28D9', purple2:'EDE9FE', rose:'BE123C', rose2:'FFE4E6', slate2:'E2E8F0' };
function t(s, text, x, y, w, h, o={}) { s.addText(text, { x, y, w, h, fontFace:'Noto Sans CJK TC', fontSize:o.size||14,
  bold:!!o.bold, color:o.color||C.text, align:o.align||'left', valign:o.valign||'top', margin:o.margin??0.05,
  fit:'shrink', breakLine:true, paraSpaceAfterPt:o.gap??4 }); }
function box(s, text, x, y, w, h, o={}) { s.addShape(pptx.ShapeType.roundRect,{x,y,w,h,rectRadius:0.08,
  fill:{color:o.fill||C.white}, line:{color:o.line||C.line,width:o.width||1,dash:o.dash||'solid'}});
  t(s,text,x+0.1,y+0.1,w-0.2,h-0.2,{size:o.size||13.5,bold:o.bold!==false,align:o.align||'center',valign:'mid',margin:0}); }
function bg(s){ s.background={color:C.bg}; s.addShape(pptx.ShapeType.rect,{x:0,y:0,w:13.333,h:7.5,fill:{color:C.bg},line:{color:C.bg}}); }
function head(s, title, tag){ t(s,title,0.62,0.32,8.8,0.42,{size:20,bold:true}); if(tag)t(s,tag,9.55,0.39,3.1,0.28,{size:10.5,color:C.muted,align:'right'}); s.addShape(pptx.ShapeType.line,{x:0.62,y:0.93,w:12.05,h:0,line:{color:C.line,width:1}}); }
function foot(s,n){ t(s,String(n).padStart(2,'0'),12.28,7.08,0.42,0.22,{size:9,color:C.muted,align:'right'}); }
function bullets(s, arr, x, y, w, h, size=14.5){ t(s,arr.map(v=>'• '+v).join('\n'),x,y,w,h,{size,gap:7}); }
function arrow(s,x1,y1,x2,y2,c='334155'){ s.addShape(pptx.ShapeType.line,{x:x1,y:y1,w:x2-x1,h:y2-y1,line:{color:c,width:1.3,endArrowType:'triangle'}}); }
function table(s, rows, x, y, colW, rh=0.58){ rows.forEach((r,i)=>{let cx=x;r.forEach((v,j)=>{s.addShape(pptx.ShapeType.rect,{x:cx,y:y+i*rh,w:colW[j],h:rh,fill:{color:i?C.white:C.slate2},line:{color:C.line,width:0.7}});t(s,v,cx+0.07,y+i*rh+0.08,colW[j]-0.14,rh-0.12,{size:i?11:11.5,bold:!i,align:'center',valign:'mid',margin:0});cx+=colW[j];});});}
function notes(s,n){ if(typeof s.addNotes==='function')s.addNotes(n); }
function slide(title, tag, fn){ const s=pptx.addSlide(); bg(s); head(s,title,tag); fn(s); foot(s,++slide.n); return s; } slide.n=0;

// 1 Cover
{ const s=pptx.addSlide(); bg(s); s.addShape(pptx.ShapeType.rect,{x:0,y:0,w:5.25,h:6.95,fill:{color:'0F172A'},line:{color:'0F172A'}});
box(s,'論文口試報告｜30 min',0.72,0.56,2.05,0.34,{fill:C.blue2,line:C.blue2,size:10});
t(s,'單房間非連網家電環境影響學習之\n稀疏感測空間數位孿生原型',0.72,1.35,4.15,1.45,{size:26,bold:true,color:C.white});
t(s,'A Sparse-Sensing Spatial Digital Twin for Learning Environmental Impacts of Non-Networked Appliances in a Single Room',0.72,3.05,4.05,0.95,{size:13.5,color:'CBD5E1'});
t(s,'林昀佑｜指導教授：易昶霈教授、沈慧宇副教授',0.72,6.43,4.15,0.35,{size:11.5,color:'E5E7EB'});
box(s,'核心定位',6.25,1.0,1.2,0.42,{fill:C.purple2,line:C.purple2,size:11});
t(s,'不是單純 MCP / Web demo，\n而是 Agent-ready indoor spatial digital twin。',6.25,1.65,5.7,0.85,{size:22,bold:true});
bullets(s,['少量感測器推估房間內三因子空間場','學習冷氣、窗戶、燈光等非連網設備影響','將數位孿生核心封裝為 AI Agent 可呼叫工具'],6.3,3.0,5.8,1.35,15.5);
box(s,'可解釋｜可校正｜可工具化',6.3,5.25,5.15,0.62,{fill:C.white,line:C.line,size:19}); notes(s,'開場強調研究主體是數位孿生核心與 Agent tool interface。'); foot(s,1); slide.n=1; }

slide('研究問題：普通房間沒有完整環境場','Problem setting',s=>{ box(s,'現實住宅',0.8,1.35,2.2,0.58,{fill:C.slate2,line:'94A3B8'}); bullets(s,['設備多半沒有 API','感測器數量有限','不同位置體感不同'],0.95,2.18,3.0,1.05,13.5); box(s,'研究問題',4.85,1.25,3.65,0.62,{fill:C.blue2,line:C.blue,size:18}); t(s,'在稀疏感測與非連網家電條件下，如何估計單房間內溫度、相對濕度與照度的空間分布，並推論設備對環境的影響？',4.35,2.2,4.6,1.35,{size:18,bold:true,align:'center'}); box(s,'數位孿生需求',10.0,1.35,2.2,0.58,{fill:C.green2,line:C.green}); bullets(s,['可查詢特定座標','可模擬設備狀態','可供 Agent 決策輔助'],9.85,2.18,2.8,1.05,13.2); arrow(s,3.7,2.35,4.35,2.35,C.blue); arrow(s,9.1,2.35,9.75,2.35,C.green); box(s,'本研究處理的是「空間環境狀態重建」與「設備影響學習」，不是一般智慧家電控制平台。',1.55,5.35,10.25,0.7,{fill:C.white,line:C.line,size:17}); });
slide('研究缺口：插值知道距離，但不知道設備語意','Research gap',s=>{ table(s,[['方法類型','優點','限制'],['一般感測器監控','容易實作、能記錄時間序列','只能觀察測點，無法形成完整空間場'],['IDW / 空間插值','簡單、可作 baseline','只考慮距離，不理解冷氣、窗戶、燈光'],['純黑箱模型','可能提高預測精度','缺乏設備與幾何語意，難以解釋'],['本研究','結合幾何、設備、稀疏感測校正','限制在單房間 prototype 與分層驗證']],0.75,1.35,[2.15,4.4,5.25],0.68); box(s,'關鍵差異：本研究不是把感測值直接插值，而是先建立可解釋環境模型，再用感測器殘差修正。',1.2,5.75,10.7,0.62,{fill:C.blue2,line:C.blue,size:16}); });
slide('總體貢獻：四個層次','Contributions',s=>{ [['1\n三因子空間數位孿生','溫度、相對濕度、照度\n同時估計房間內座標狀態',C.blue2,C.blue],['2\n非連網設備影響學習','用 before/after 觀測\n學習冷氣、窗戶、燈光影響',C.green2,C.green],['3\n稀疏感測校正','power calibration\ntrilinear residual correction',C.amber2,C.amber],['4\nAgent 工具介面','查詢、模擬、影響學習\n候選動作排序',C.purple2,C.purple]].forEach((c,i)=>{let x=0.8+i*3.12;box(s,c[0],x,1.45,2.55,1.0,{fill:c[2],line:c[3],size:16});t(s,c[1],x+0.1,2.72,2.35,1.0,{size:13.5,align:'center'});}); box(s,'主張邊界：本研究證明的是單房間稀疏感測條件下的 prototype 與分層驗證，不宣稱已完成多房間泛化或真實閉迴路控制。',1.0,5.15,11.25,0.78,{fill:C.white,line:C.rose,size:16}); });
slide('系統架構：從房間語意到 Agent 工具','System architecture',s=>{ const xs=[0.65,3.0,5.35,7.7,10.05], labels=['Room schema\ngeometry / devices','Sparse sensing\ncorner sensors','Digital twin core\nthree-factor fields','Calibration / learning\nresidual + impact','Agent tool layer\nquery / simulate / rank']; labels.forEach((l,i)=>box(s,l,xs[i],2.05,1.95,1.05,{fill:[C.slate2,C.blue2,C.green2,C.amber2,C.purple2][i],line:['94A3B8',C.blue,C.green,C.amber,C.purple][i],size:12.5})); for(let i=0;i<4;i++)arrow(s,xs[i]+1.95,2.58,xs[i+1],2.58); bullets(s,['MCP 是其中一種工具協定實作；論文主體應放在 Agent 可呼叫的 digital twin core','Web demo 是展示層；不應取代方法與驗證層敘事','模型、校正、工具化三者要分層描述'],1.05,4.55,11.2,1.2,14.5); });
slide('三因子模型：變數專屬 reduced-order nominal model','Variable-specific modeling',s=>{ table(s,[['因子','主要來源','模型語意'],['溫度','冷氣、窗戶、燈光熱效應','熱交換、設備距離衰減、空間分布'],['相對濕度','冷氣除濕、開窗換氣、外部濕度','水氣交換與設備狀態影響'],['照度','窗戶自然光、燈光、遮蔽與反射','幾何光照、距離衰減、家具遮蔽']],1.0,1.5,[1.6,4.25,5.35],0.72); box(s,'方法定位：不是三個因子套同一個插值公式，而是依照變數特性建立 nominal model。',1.25,5.15,10.6,0.68,{fill:C.green2,line:C.green,size:16.5}); });
slide('稀疏感測校正：從少量觀測補正整體空間場','Sparse calibration',s=>{ ['Nominal prediction','Sensor residuals','Trilinear correction','Corrected field'].forEach((v,i)=>box(s,v,[0.95,4.1,7.25,10.35][i],1.7,[2.35,2.35,2.35,2.1][i],0.75,{fill:[C.slate2,C.blue2,C.green2,C.amber2][i],line:['94A3B8',C.blue,C.green,C.amber][i]})); arrow(s,3.3,2.08,4.1,2.08,C.blue); arrow(s,6.45,2.08,7.25,2.08,C.green); arrow(s,9.6,2.08,10.35,2.08,C.amber); bullets(s,['active-device power calibration：根據設備附近誤差調整設備影響強度','trilinear residual correction：用角落感測器殘差修正房間內部估計','校正目標是吸收真實觀測差異，而不是取代原本的物理／幾何模型'],1.15,4.15,10.9,1.25,15); });
slide('非連網家電影響學習：用環境變化反推設備效果','Impact learning',s=>{ ['Before\n設備作用前','After\n設備作用後','Delta field\n影響場','Impact model\n設備參數'].forEach((v,i)=>box(s,v,[1,4,7,10][i],1.65,2,0.85,{fill:i<2?C.white:i==2?C.blue2:C.green2,line:i<2?C.line:i==2?C.blue:C.green})); arrow(s,3,2.08,4,2.08); arrow(s,6,2.08,7,2.08); arrow(s,9,2.08,10,2.08); table(s,[['設備','學習／模擬的主要影響'],['冷氣','降溫、除濕、距離與方向性影響'],['窗戶','外部溫濕度、日照、開啟比例影響'],['燈光','照度提升與局部熱效應']],2.0,4.2,[2.15,7.1],0.58); });
slide('Hybrid residual neural network：黑箱只學剩餘誤差','Residual learning',s=>{ ['可解釋主模型','+ 感測器校正','+ 殘差神經網路','= 最終估計場'].forEach((v,i)=>box(s,v,[1,4,7,10][i],1.6,[2.4,2.4,2.4,2.25][i],0.72,{fill:[C.green2,C.blue2,C.purple2,C.amber2][i],line:[C.green,C.blue,C.purple,C.amber][i],size:17})); arrow(s,3.4,1.96,4,1.96); arrow(s,6.4,1.96,7,1.96); arrow(s,9.4,1.96,10,1.96); bullets(s,['神經網路不是取代數位孿生模型，而是學 nominal model 無法解釋的 residual','保留設備、幾何、因子語意，並以資料驅動方式補償誤差','口試時要避免讓審查者以為整個方法只是 black-box regression'],1.15,4.0,10.8,1.3,15); });
slide('Agent tool interface：讓模型被查詢、模擬與排序','Agent integration',s=>{ [['initialize_environment','建立房間、設備、感測器與外部條件'],['sample_point','查詢指定座標的三因子狀態'],['learn_impacts','由 before/after 資料學習設備影響'],['run_window_direct','模擬外部天氣與開窗比例'],['rank_actions','根據目標環境排序候選動作']].forEach((v,i)=>{let y=1.25+i*0.78;box(s,v[0],1,y,3.1,0.5,{fill:C.purple2,line:C.purple,size:11.5});t(s,v[1],4.35,y+0.08,6.9,0.32,{size:13.5});}); box(s,'推薦表述：MCP 是實作通道；Agent tool interface 才是論文中要強調的系統整合貢獻。',1.2,5.55,10.6,0.68,{fill:C.white,line:C.purple,size:16}); });
slide('展示層：Web demo 的正確定位','Visualization layer',s=>{ ['Digital twin core','API / tool layer','Web demo','Defense explanation'].forEach((v,i)=>box(s,v,[1,4.2,7.4,10.4][i],1.8,[2.5,2.5,2.5,1.9][i],0.72,{fill:[C.green2,C.purple2,C.blue2,C.amber2][i],line:[C.green,C.purple,C.blue,C.amber][i],size:i==3?12.8:13.5})); arrow(s,3.5,2.16,4.2,2.16); arrow(s,6.7,2.16,7.4,2.16); arrow(s,9.9,2.16,10.4,2.16); bullets(s,['Web demo 用於展示 3D 空間點、設備狀態切換與三因子分布','它不是主要方法，也不是主要驗證來源','口試時應用它輔助說明模型輸入、輸出與系統流程'],1.2,4.1,10.8,1.2,15); });
slide('驗證設計：分層驗證，不混淆證據層級','Evaluation design',s=>{ table(s,[['層級','驗證目的','不能過度宣稱'],['受控模擬','檢查模型是否能重建合理空間場','不能等同真實房間完整驗證'],['IDW baseline','比較設備語意模型與純距離插值','不能只看單一情境'],['Ablation','檢查各模組是否有貢獻','不能說所有指標必然改善'],['真實臥室 snapshot','驗證 sparse calibration 對保留點有幫助','不能宣稱完整 3D ground truth'],['Public benchmark','補充 task-aligned 外部比較','不能說完全驗證本系統']],0.65,1.2,[2.0,5.05,5.0],0.55); });
slide('結果一：受控模擬與 IDW baseline','Controlled simulation',s=>{ [['IDW baseline',['只看感測點距離','缺少冷氣／窗戶／燈光位置語意','設備影響明顯時容易失真'],C.rose2,C.rose],['本研究模型',['使用設備影響函數','保留房間幾何與因子差異','再用感測器殘差修正'],C.blue2,C.blue],['結論',['模型價值來自設備語意','不是單純增加參數','適合 sparse sensing 場景'],C.green2,C.green]].forEach((v,i)=>{let x=[1,5.35,9.55][i];box(s,v[0],x,1.45,[2.5,2.5,2.3][i],0.72,{fill:v[2],line:v[3],size:18});bullets(s,v[1],x+0.05,2.45,[3.1,3.1,2.85][i],1.1,13.2);}); box(s,'報告時應說明：IDW 是合理 baseline，但不是能處理非連網設備影響的充分模型。',1.2,5.6,10.6,0.62,{fill:C.white,line:C.line,size:16}); });
slide('結果二：消融分析檢查每個模組的角色','Ablation study',s=>{ table(s,[['移除模組','觀察重點'],['without reflection / geometry detail','照度與遮蔽相關誤差變化'],['without power calibration','設備附近誤差是否放大'],['without trilinear correction','角落感測器殘差是否無法傳遞到內部空間'],['without hybrid residual NN','是否缺少資料驅動補償能力']],1.1,1.35,[3.9,7.2],0.65); box(s,'Ablation 的用法：證明系統不是功能堆疊，而是每一層都對特定誤差來源有對應作用。',1.3,5.55,10.4,0.62,{fill:C.amber2,line:C.amber,size:16}); });
slide('結果三：真實臥室 snapshot 的定位','Real-bedroom snapshot',s=>{ [['可以主張',['真實觀測可被納入校正流程','保留點估計可用來檢查校正效果','可證明 prototype 與真實場域銜接'],C.green2,C.green],['不要主張',['已完整驗證 3D dense field','已泛化到所有房型','已完成閉迴路控制實驗'],C.rose2,C.rose],['論文寫法',['稱為 snapshot validation','明確標註 claim boundary','搭配模擬與 benchmark 補足'],C.blue2,C.blue]].forEach((v,i)=>{let x=[1,5,9][i];box(s,v[0],x,1.45,2.2,0.6,{fill:v[2],line:v[3]});bullets(s,v[1],x+0.05,2.3,3.35,1.3,13.5);}); });
slide('結果四：公開資料集作為 task-aligned benchmark','External benchmarks',s=>{ [['SML2010','用於補充室內環境預測相關任務比較',C.blue2,C.blue],['CU-BEMS','用於補充建築能源與環境感測任務比較',C.amber2,C.amber],['正確定位','沒有完整房間幾何\n沒有 8 角落感測配置\n不是 3D dense-field ground truth',C.rose2,C.rose]].forEach((v,i)=>{let x=[1,5.4,9.55][i];box(s,v[0],x,1.6,2.45,0.7,{fill:v[2],line:v[3],size:18});t(s,v[1],x-0.05,2.65,2.75,0.95,{size:13,align:'center'});}); box(s,'結論：公開資料集能補充外部任務相容性，但不能替代本研究的空間場驗證。',1.25,5.4,10.6,0.62,{fill:C.white,line:C.line,size:16}); });
slide('擬新增延伸：自由空間與模組化 estimator','Proposed extension',s=>{ box(s,'目前主線\nPhysics spine',0.95,2.1,2.2,0.85,{fill:C.green2,line:C.green,size:15}); box(s,'自由空間拓樸\nΩ_room / Ω_occ / Ω_free',3.95,1.45,2.7,0.85,{fill:C.white,line:C.purple,dash:'dash',size:12.5}); box(s,'節點語義\nV_geom / V_obs / V_target',3.95,2.75,2.7,0.85,{fill:C.white,line:C.purple,dash:'dash',size:12.5}); box(s,'模組化 estimator\nIDW / 2D / 3D / Cell-IDW',7.45,2.1,2.8,0.85,{fill:C.white,line:C.purple,dash:'dash',size:12.5}); box(s,'Confidence / provenance\nblocked CV / intervention',10.85,2.1,1.85,0.85,{fill:C.white,line:C.purple,dash:'dash',size:11.5}); arrow(s,3.15,2.52,3.95,1.88,C.purple); arrow(s,3.15,2.52,3.95,3.18,C.purple); arrow(s,6.65,2.18,7.45,2.52,C.purple); arrow(s,6.65,3.18,7.45,2.52,C.purple); arrow(s,10.25,2.52,10.85,2.52,C.purple); bullets(s,['虛線外框表示 proposed extension，不放進已完成驗證主張','可放在 future work 或系統擴充章節','用來表達系統不是純樹狀，而是多模組互相關聯'],1.1,4.85,10.9,1.0,14); });
slide('限制與風險：提前講清楚比較安全','Limitations',s=>{ table(s,[['類別','限制','對應說法'],['資料限制','真實資料為單房間 snapshot，缺完整 dense-field ground truth','定位為 prototype 與保留點驗證'],['方法限制','reduced-order 模型是工程近似，hybrid residual 需防 overfitting','保留可解釋主模型並明確標註誤差來源'],['系統限制','Agent/MCP 是工具化層，尚非真實閉迴路控制','稱為 counterfactual ranking 與 decision support']],0.8,1.45,[1.8,5.45,4.5],0.78); box(s,'限制不是弱點，而是 claim boundary。只要證據層次與主張層次對齊，論文會更可信。',1.25,5.7,10.55,0.62,{fill:C.white,line:C.line,size:16}); });
slide('口試敘事主線：從問題到貢獻','Defense storyline',s=>{ ['普通房間缺完整環境場','建立三因子可解釋模型','用稀疏感測校正','學習非連網設備影響','提供 Agent 工具化使用'].forEach((v,i)=>{let x=0.75+i*2.45;box(s,`${i+1}\n${v}`,x,1.7+(i===4?1.15:0),2.05,0.82,{fill:i===4?C.purple2:C.blue2,line:i===4?C.purple:C.blue,size:12.5}); if(i<4)arrow(s,x+2.05,2.1,x+2.45,i===3?3.25:2.1);}); ['可解釋','可校正','可工具化'].forEach((v,i)=>box(s,v,[1.2,3.3,5.4][i],5.1,[1.8,1.8,2.0][i],0.55,{fill:C.white,line:[C.green,C.blue,C.purple][i],size:18})); t(s,'不建議一直講「我做了 MCP」；建議說「我把 digital twin core 做成 Agent 可以使用的 tool interface」。',8.1,4.82,4.2,0.92,{size:15,bold:true}); });
slide('結論：本研究的主要貢獻','Conclusion',s=>{ [['1','提出單房間稀疏感測三因子空間數位孿生原型。',C.blue],['2','以變數專屬 reduced-order nominal model 保留溫度、濕度、照度的物理與幾何語意。',C.green],['3','結合 power calibration、trilinear residual correction 與 hybrid residual NN 改善估計。',C.purple],['4','把模型封裝為 Agent 可呼叫工具介面，支援查詢、模擬、影響學習與反事實排序。',C.amber]].forEach((v,i)=>{let y=1.48+i*1.05;box(s,v[0],1,y,0.55,0.55,{fill:v[2],line:v[2],color:C.white,size:18});t(s,v[1],1.85,y+0.08,10.4,0.4,{size:17,bold:true});}); box(s,'最終定位：不是一般插值，也不是單純 Web/MCP demo，而是 Agent-ready indoor spatial digital twin。',1.35,6.1,10.7,0.65,{fill:C.white,line:C.line,size:18}); });

const out = process.argv[2] || 'outputs/papers/thesis_presentation_agent_zh.pptx';
fs.mkdirSync(path.dirname(out), { recursive: true });
pptx.writeFile({ fileName: out });
